name: Tests

on:
  push:
    branches:
      - ext-3.2/3.3
  pull_request:
    branches:
      - ext-3.2/3.3

jobs:
  call-tests:
    name: Extension tests
    uses: phpbb-extensions/test-framework/.github/workflows/tests.yml@3.3.x
    with:
      EXTNAME: vinny/shareon
